name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.16.x"]
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install goyacc
        run: |
          go get golang.org/x/tools/cmd/goyacc@latest
      - uses: actions/checkout@v2
      - name: Check style
        run: |
          gofmt -w .
          git diff --exit-code
      - name: Compile
        run: |
          make
          git diff --exit-code
